name: New CICD
on:
  push:
jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      # - run: echo "hello"
      - name: Checkout code
        uses: actions/checkout@v5
      # - name: List files
      #   run: |
      #     ls -l ${{ github.workspace }}
      - name: Install dependencies
        run: npm ci
      - name: run tests
        run: |
          #  npm install 
          npm test
  lint:
    name: Static Code analysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: run lint
        run: npm run lint
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    needs: [test,lint]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: Build
        run: |
          npm run build
      # - name: Store artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          path: dist


