name: New CICD
on:
  push:
jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      # - run: echo "hello"
      - &checkout
        name: Checkout code
        uses: actions/checkout@v5
      # - name: List files
      #   run: |
      #     ls -l ${{ github.workspace }}
      - &setup_node
        name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - &install_dependencies
        name: Install dependencies
        run: npm ci
      - name: run tests
        run: |
          #  npm install 
          npm test
  lint:
    name: Static Code analysis
    runs-on: ubuntu-latest
    steps:
      - *checkout
      # - name: checkout code
      #   uses: actions/checkout@v5
      - *setup_node
      - *install_dependencies
      - name: run lint
        run: npm run lint
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    needs: [test,lint]
    steps:
      - *checkout
      - *setup_node
      - *install_dependencies
      - name: Build
        run: |
          npm run build
      # - name: Store artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          path: dist
  docker:
    name: Build docker
    runs-on: ubuntu-latest
    needs: [build]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }}
    steps:
      - *checkout
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to gcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{steps.meta.outputs.tags.sha}}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          
          

